###Numerical computing with numpy

In [1]:
w1,w2,w3=0.3,0.2,0.5

In [2]:
kanto=[73,67,43]
johto=[91,88,64]
hoenn=[87,134,58]
sinnoh=[102,43,37]
unova=[69,96,70]

In [3]:
weights=[w1,w2,w3]

function to calculate crop yield

In [4]:
def crop_yield(region,weight):
  result=0
  for x,w in zip(region,weight):#zip is to pairs out region and weight
    result+=w*x
  return result

In [5]:
crop_yield(sinnoh,weights)

57.699999999999996

In [6]:
import numpy as np


In [7]:
kanto=np.array([73,67,43])

In [8]:
weights=np.array([w1,w2,w3])

Dot product of numpy can be calculated by np.dot(array1,array2)

In [9]:
np.dot(kanto,weights)

56.8

In [10]:
#python List
arr1=list(range(1000000))
arr2=list(range(1000000,2000000))

In [11]:
arr1_np=np.array(arr1)
arr2_np=np.array(arr2)

In [12]:
%%time
result=0
for x,y in zip(arr1,arr2):
  result+=x*y
print(result)

833332333333500000
CPU times: user 317 ms, sys: 3.85 ms, total: 321 ms
Wall time: 368 ms


In [13]:
%%time
print(np.dot(arr1,arr2))

833332333333500000
CPU times: user 270 ms, sys: 11.7 ms, total: 282 ms
Wall time: 317 ms


In [14]:
input_np=np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]])

In [15]:
weights.dtype

dtype('float64')

###Multiplication of matrix

In [16]:
np.matmul(input_np,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [17]:
input_np @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [18]:
import urllib.request

In [19]:
urllib.request.urlretrieve('https://gist.githubusercontent.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv','climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f6368c3d6d0>)

In [20]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [21]:
climate_data.shape

(10000, 3)

In [22]:
yields=climate_data @ weights

In [23]:
yields.shape

(10000,)

In [24]:
from numpy.core.multiarray import concatenate
climate_result=concatenate((climate_data,yields.reshape(10000,1)),axis=1)

In [25]:
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [26]:
np.savetxt('climate_result.txt',climate_result,fmt='%.2f',header='Temperature,Rainfall,Humidity,Yield_apples',comments="")

###Arithmetic operations, broadcasting and comparison
Numpy arrays support arithmetic operators like +, -, *, etc. You can perform an arithmetic operation with a single number (also called scalar) or with another array of the same shape. Operators make it easy to write mathematical expressions with multi-dimensional arrays

In [27]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [28]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [29]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [30]:
# Adding a scalar
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [31]:
# Element-wise subtraction
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [32]:
# Division by scalar
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [33]:
# Element-wise multiplication
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [34]:
# Modulus with scalar
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

In [35]:
#intexing
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [37]:
arr3[0,1,2]   #0 from

15.0